package:
  name: py-l8angles
  version: "0.1"

source:
  #path: ../../
  git_url: https://github.com/Swordman51/l8-angles-master
  git_depth: -1

requirements:
  build:
    - python
    - cython
    - setuptools
    - numpy

  run:
    - python 
    - numpy

#test:
 # imports:
  #  - l8angles
